FROM mcr.microsoft.com/dotnet/sdk:8.0 AS migrate

WORKDIR /src

COPY ["TimeTrackerApi/TimeTrackerApi.csproj", "TimeTrackerApi/"]
RUN dotnet restore "TimeTrackerApi/TimeTrackerApi.csproj"

COPY . .
WORKDIR "/src/TimeTrackerApi"

ENTRYPOINT ["dotnet", "ef", "database", "update"]