FROM mcr.microsoft.com/dotnet/sdk:8.0 AS migrate

WORKDIR /src

RUN dotnet tool install --global dotnet-ef

COPY ["TimeTrackerApi/TimeTrackerApi.csproj", "TimeTrackerApi/"]
RUN dotnet restore "TimeTrackerApi/TimeTrackerApi.csproj"

COPY . .
WORKDIR "/src/TimeTrackerApi"
ENV PATH="$PATH:/root/.dotnet/tools"
ENTRYPOINT ["dotnet", "ef", "database", "update"]