FROM mcr.microsoft.com/dotnet/sdk:8.0 AS migrate

WORKDIR /src

COPY ./TimeTrackerApi.csproj /src/TimeTrackerApi/
COPY . /src/TimeTrackerApi/

RUN dotnet restore "/src/TimeTrackerApi/TimeTrackerApi.csproj"

ENTRYPOINT ["dotnet", "ef", "database", "update", "--project", "/src/TimeTrackerApi/TimeTrackerApi.csproj"]
